version: "2"
# Local Database
# Containerized but using a local data folder for persistence
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_local
    ports:
      - 3306:3306
    env_file: ./maria/.env
    volumes:
      # Database data folder
      # local hidden dir in the user root is used for this, so destroying the container wont delete the db data
      - /Users/Shared/.dm/maria/data:/var/lib/mysql
    networks:
      - bridge

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    ports:
      - 4444:4444
    networks:
      - bridge

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - bridge

networks:
    bridge:
      driver: bridge